name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Yarn install
        run: npx yarn install
      - name: Build
        run: npx yarn build

      - uses: actions/checkout@v4
        with:
          ref: 'deploy'
      - name: Commit changes
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
          add: "./dist --force"
          pull: "--rebase --autostash ."
          push: "origin deploy --force"
          message: "autom: build"
          default_author: github_actions
